# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
set_property ip_repo_paths {
  /home/derek/Documents/year_4/ECE532/ip_repo/hasher_1.0
  /home/derek/Documents/year_4/ECE532/ip_repo/hasher_1.0
} [current_fileset]
read_verilog -library xil_defaultlib {
  /home/derek/Documents/year_4/ECE532/ip_repo/hasher_1.0/src/seven_segment.v
  /home/derek/Documents/year_4/ECE532/ip_repo/hasher_1.0/src/mix_hash.v
  /home/derek/Documents/year_4/ECE532/ip_repo/hasher_1.0/hdl/hasher_v1_0_S00_AXI.v
  /home/derek/Documents/year_4/ECE532/ip_repo/hasher_1.0/hdl/hasher_v1_0.v
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/derek/Documents/year_4/ECE532/ip_repo/hasher_1.0/hasher_v1_0_project/hasher_v1_0_project.cache/wt [current_project]
set_property parent.project_dir /home/derek/Documents/year_4/ECE532/ip_repo/hasher_1.0/hasher_v1_0_project [current_project]
synth_design -top hasher_v1_0 -part xc7a100tcsg324-1
write_checkpoint hasher_v1_0.dcp
report_utilization -file hasher_v1_0_utilization_synth.rpt -pb hasher_v1_0_utilization_synth.pb
