# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib D:/Libraries/University/ECE532/IP/bram_tester_ip/bram_tester_ip.srcs/sources_1/new/tester.v
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Libraries/University/ECE532/IP/bram_tester_ip/bram_tester_ip.cache/wt [current_project]
set_property parent.project_dir D:/Libraries/University/ECE532/IP/bram_tester_ip [current_project]
synth_design -top bram_tester -part xc7a100tcsg324-1
write_checkpoint bram_tester.dcp
report_utilization -file bram_tester_utilization_synth.rpt -pb bram_tester_utilization_synth.pb
